### PR TITLE
Fix the topic saving from the admin, fix #346

### LINKED ISSUE #346: Fix the topic saving from the admin
Including "featured" boolean.

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

File: js/components/topic/details.vue [hunk 1]
```diff
@@ -37,13 +37,13 @@ export default {
             this.toggled = !this.toggled;
         },
         save: function(e) {
-            if (this.$refs.form.$refs.form.validate()) {
-                var data = this.$refs.form.$refs.form.serialize();
-
-                this.topic.save(data);
+            const form = this.$refs.form.$refs.form;
```
Comment (noirbizarre) [inline js/components/topic/details.vue]: weird :)

**Comment by noirbizarre** [comment]
r+
